const products = [
    {
        id:"1",
        category: "libros",
        autor: "Rosa León",
        name: "¿Vieja Yo? Cómo reinventarse con éxito a cualquier edad",
        price: 29.99,
        stock: 20,
        description: "La mayoría de las personas, al llegar a cierta edad, creen que su mundo va en declive, y no es solo que algunos se sienten así, sino que la sociedad ha impuesto ciertas reglas y pensamientos, totalmente equivocados y desfasados, que aún siguen escuchándose por los rincones, haciendo sentirse “viejas” a las personas, pero con el peor de los significados que dicha palabra pueda tener. Y peor aún, es que la gran mayoría se lo cree, y he allí el craso error que están cometiendo. La vejez y el modo de vivirla ha ido cambiando a través de los años, porque los estilos de vida se han ido modificando. Considerar a una persona de más de cincuenta años muy vieja para reinventarse es totalmente ridículo, la edad no tiene nada que ver ni con el talento, las ganas y los deseos de cambiar tu vida del modo que puedas disfrutarla de la forma que deseas. ¿Qué no es igual que a los veinte? No, no lo es, pero no deja de ser maravilloso aprovechar la experiencia, la sobre cualificación que se tiene, e incluso continuar informándose. Y me atrevo a decir que, continuar preparándose para lograr lo que se desea, alarga la vida porque la llena de renovada energía y deseos de vivir por lograr el nuevo reto. ¿Vieja Yo? Cómo reinventarse con éxito a cualquier edad, es un libro potenciador. Y peor aún, es que la gran mayoría se lo cree, y he allí el craso error que están cometiendo. La vejez y el modo de vivirla ha ido cambiando a través de los años, porque los estilos de vida se han ido modificando. Considerar a una persona de más de cincuenta años muy vieja para reinventarse es totalmente ridículo, la edad no tiene nada que ver ni con el talento, las ganas y los deseos de cambiar tu vida del modo que puedas disfrutarla de la forma que deseas. ¿Qué no es igual que a los veinte? No, no lo es, pero no deja de ser maravilloso aprovechar la experiencia, la sobre cualificación que se tiene, e incluso continuar informándose. Y me atrevo a decir que, continuar preparándose para lograr lo que se desea, alarga la vida porque la llena de renovada energía y deseos de vivir por lograr el nuevo reto. ¿Vieja Yo? Cómo reinventarse con éxito a cualquier edad, es un libro potenciador.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/libro1_mdzwly.jpg",
    },
    {
        id:"2",
        category: "libros",
        autor: "Rosa León",
        name: "Me, old? How to successfully reinvent yourself at any age",
        price: 29.99,
        stock: 15,
        description: "Most people, upon reaching a certain age, believe that their world is in decline, and it is not just that some people feel that way, but that society has imposed certain rules and ideas, totally wrong and out of date, that can still be heard in corners, making people feel “old”, but with the worst meaning the word can have. And what is worse: the vast majority believe it, and that is the huge mistake they are making. Old age and the way we experience it have changed over the years, because lifestyles have changed. Considering a person over fifty too old to reinvent themselves is totally ridiculous; age has nothing to do with talent, drive, and desire to change your life so that you can enjoy it the way you want. That it is not the same as at twenty? No, it is not, but it is still wonderful to take advantage of the experience, the over-qualification that one now has, and even to continue learning. And I dare to say that continuing to prepare to achieve what you want lengthens your life because it fills you with renewed energy and the desire to live to achieve the new challenge. Me, old? How to successfully reinvent yourself at any age is an empowering book. I draw on my own experience of personal growth and professional reinvention. Based on my mistakes, weaknesses, and learnings, I show a summary of the path I have traveled throughout these years to successfully reinvent myself, including my last reinvention at age fifty and how I did it. I share the most outstanding facts that I myself have internalized to change my life, and I also provide you with thirty of the exercises that I work on and that I assure you can help you review yourself, get to know yourself, develop your best version, and get up from your chair to reinvent your life and pursue your dreams and projects. Soon I plan to write the second part of this book, focusing more on the aspects of entrepreneurship and business creation as a part of professional reinvention, because believe me when I tell you that nothing, nothing is impossible in terms of comprehensive reinvention, both personal and professional, if you want it. You create what you believe. Vibrate positively!",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678207/samples/redacteca/libro1.1_l9glyr.jpg",
    },
    {
        id:"3",
        category: "ebooks",
        autor: "Rosa León",
        name: "¿Estás viviendo tu vida o la de alguien más?",
        price: 4.99,
        stock: 10,
        description: "Hemos creado un e-book con algunas características que te pueden ayudar a revisar si estás o no viviendo tu propia vida. Todos queremos vivir la vida que soñamos, sin embargo con el tiempo nos dejamos envolver por las personas que nos rodean y comenzamos a adoptar posturas y actitudes que no son realmente nuestras y vamos perdiendo nuestra esencia. También te incluimos un ejercicio de preguntas poderosas para que inicies tu proceso de autoconocimiento.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/ebook1_lrvypt.png",
    },
    {
        id:"4",
        category: "ebooks",
        autor: "Rosa León",
        name: "112 Nichos de Mercado",
        price: 4.99,
        stock: 10,
        description: "Encontrar un nicho de mercado —y descubrir nuevos nichos a lo largo del tiempo— es fundamental para construir un negocio exitoso. Sin embargo, saber qué mercado atacar ¡puede ser un desafío para muchos emprendedores!",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/ebook1_lrvypt.png",
    },
    {
        id:"5",
        category: "ebooks",
        autor: "Rosa León",
        name: "5 Pasos Para Planificar tu Día con Éxito cuando eres Emprendedor",
        price: 7.99,
        stock: 10,
        description: "Estos 5 pasos para planificar tu día con éxito cuando eres emprendedor, no sólo te ayudará en tu negocio sino te aportará para tu vida en general, cualquier actividad que hagas, ya sea en tu hogar, con la familia, amigos, clases, entre otras, es la mejor  herramienta y respuesta a tus problemas.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/ebook1_lrvypt.png",
    },
    {
        id:"6",
        category: "ebooks",
        autor: "Rosa León",
        name: "10 Tips para Organizar Eventos Virtuales",
        price: 7.99,
        stock: 10,
        description: "Este libro te permitirá obtener el conocimiento necesario para realizar cualquier tipo de evento virtual que desees de acuerdo a tus objetivos. De esta manera que te brindará 10 tips para organizar dichos eventos, te funcionara de manera exitosa si estas empezando a emprender.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1660102587/samples/redacteca/112A27B9-2973-4F46-AA36-84714FFDC2DE_ifiob6.png",
    },
    {
        id:"7",
        category: "libros",
        autor: "Rosa León",
        name: "Buddy",
        price: 24.99,
        stock: 20,
        description: "Buddy fue el perro de mi esposo y se conocieron cuando Matt estaba en la universidad, Vivieron juntos por nueve años y fueron muchas las aventuras que ambos pasaron. Buddy fue siempre la mejor compañía que Matt pudo tener en los tiempos difíciles. Este es un tributo para un amigo increíble y un regalo para mi amado compañero de vida.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1660103004/samples/redacteca/41jluMSJtlL._SX331_BO1_204_203_200__mr4vzz.jpg",
    },
    {
        id:"8",
        category: "libros",
        autor: "Rosa León",
        name: "Andrea, the little bear, tries to sleep in the lair",
        price: 24.99,
        stock: 20,
        description: "My daughter Andrea was very special when it came to sleep time. Her sister Rossanna could sleep even while eating, but Andrea fought falling asleep all the time. We tried everything at home to allow her to sleep. Andrea enjoyed most being walked in the stroller, but when she finally fell asleep in the stroller and moved her to the crib she would awake and we would have to start the routine all over again. Today I laugh remembering those hard nights, but I know many parents around the world are having similar troubles with their own children. This story, based on my experience with my lovely Andrea, maybe can help you with your little angels so every night they can take the journey to the dreamland.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1660103377/samples/redacteca/31NGel1WwXL._SX260__wcu3gy.jpg",
    },
    {
        id:"9",
        category: "libros",
        autor: "Rosa León",
        name: "Diario de una migrante venezolana",
        price: 30,
        stock: 20,
        description: "Soy mujer, hija, madre, esposa y venezolana de nacimiento. Como muchos compatriotas salí de mi tierra en busca de una mejor calidad de vida. Esta es parte de mi historia como migrante. He sido afortunada, no me ha tocado caminar ni dormir en el frío como lo están haciendo muchos de mis hermanos venezolanos en este momento. Con estos pasajes solo quiero contar un poco de lo que he vivido y aprendido los últimos cinco años. A lo mejor lo que necesito es exorcizar demonios de tristeza, impotencia, añoranzas y algunas veces soledad; o solo quiero dar gracias porque las circunstancias me han enseñado muchas cosas en esta etapa de mi vida. Cualquiera que sea la razón es a través de estos pasajes donde he encontrado la manera de hacerlo y espero que alguien los lea y me entienda.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1660103597/samples/redacteca/51DFXrpiy6L._SY346__c62lwu.jpg",
    },

    
]
export default products