const products = [
    {
        id:"1",
        category: "libros",
        autor: "Rosa León",
        name: "¿Vieja Yo?",
        price: 30,
        stock: 20,
        description: "Este libro trata de como reinventate después de los 50 años",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/libro1_mdzwly.jpg",
    },
    {
        id:2,
        category: "libros",
        autor: "Rosa León",
        name: "Me old?",
        price: 30,
        stock: 15,
        description: "Este libro trata de como reinventate después de los 50 años en inglés",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678207/samples/redacteca/libro1.1_l9glyr.jpg",
    },
    {
        id:3,
        category: "ebooks",
        autor: "Rosa León",
        name: "¿Estás viviendo tu vida o la de alguien más?",
        price: 5,
        stock: 10,
        description: "Este e-book cuenta con características que te pueden ayudar a revisar si estás o no viviendo tu propia vida, además incluye un ejercicio de preguntas para que inicies tu proceso de autoconocimiento.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/ebook1_lrvypt.png",
    },
    {
        id:4,
        category: "ebooks",
        autor: "Rosa León",
        name: "¿Estás viviendo tu vida o la de alguien más?",
        price: 5,
        stock: 10,
        description: "Este e-book cuenta con características que te pueden ayudar a revisar si estás o no viviendo tu propia vida, además incluye un ejercicio de preguntas para que inicies tu proceso de autoconocimiento.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/ebook1_lrvypt.png",
    },
    {
        id:5,
        category: "ebooks",
        autor: "Rosa León",
        name: "¿Estás viviendo tu vida o la de alguien más?",
        price: 5,
        stock: 10,
        description: "Este e-book cuenta con características que te pueden ayudar a revisar si estás o no viviendo tu propia vida, además incluye un ejercicio de preguntas para que inicies tu proceso de autoconocimiento.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/ebook1_lrvypt.png",
    },
    {
        id:6,
        category: "ebooks",
        autor: "Rosa León",
        name: "¿Estás viviendo tu vida o la de alguien más?",
        price: 5,
        stock: 10,
        description: "Este e-book cuenta con características que te pueden ayudar a revisar si estás o no viviendo tu propia vida, además incluye un ejercicio de preguntas para que inicies tu proceso de autoconocimiento.",
        img: "https://res.cloudinary.com/andrealeonfandino/image/upload/v1657678208/samples/redacteca/ebook1_lrvypt.png",
    },

    
]
export default products